#!/bin/bash
DOTFILES_DIR="$HOME/dotfiles/i3"
I3_CONFIG_FILE="$HOME/.config/i3/config"

function concat_files {
  cat $DOTFILES_DIR/shortcuts $DOTFILES_DIR/look $DOTFILES_DIR/apps > $I3_CONFIG_FILE
}

function restart {
  i3-msg "restart"
  polybar-msg cmd restart
}

concat_files
restart

